[colors.primary]
background = "#1C2023"
foreground = "#C7CCD1"

[colors.cursor]
text = "#1C2023"
cursor = "#C7CCD1"

[colors.vi_mode_cursor]
text = "#1C2023"
cursor = "#C7CCD1"

[colors.search.matches]
foreground = "#1C2023"
background = "#F3F4F5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#747C84"
background = "#C7CCD1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1C2023"
red = "#C7AE95"
green = "#95C7AE"
yellow = "#AEC795"
blue = "#AE95C7"
magenta = "#C795AE"
cyan = "#95AEC7"
white = "#C7CCD1"

[colors.bright]
black = "#747C84"
red = "#C7AE95"
green = "#95C7AE"
yellow = "#AEC795"
blue = "#AE95C7"
magenta = "#C795AE"
cyan = "#95AEC7"
white = "#F3F4F5"

[colors.dim]
black = "#F3F4F5"
red = "#C7AE95"
green = "#C795AE"
yellow = "#AEC795"
blue = "#AE95C7"
magenta = "#95C7AE"
cyan = "#95AEC7"
white = "#747C84"

