[font]
size = 12
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
